[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Use custom Arduino core with Bluepad32 support
platform_packages = 
    framework-arduinoespressif32 @ https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip

; Serial Monitor & USB Settings
monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    ;-DBOARD_HAS_PSRAM      ; Only keep this if your board actually has PSRAM
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=0

; Flash and Memory settings
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio ; Only if your variant has PSRAM
board_upload.flash_size = 4MB

board_build.partitions = huge_app.csv

lib_deps =
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    ayushsharma82/ElegantOTA @ ^3.1.0